targets:
  $default:
    sources:
      - lib/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/"
          output_folder: "lib/swagger_generated_code/"
